var url_base = window.location.protocol + "//" + window.location.host;
$.post(url_base+'/beneficiarios/listarBeneficiarios', {}, function (data) {
    var datos = JSON.parse(data);
    var filas;
    var cont = 0;
    var estado;
    $.each(datos, function (i, v) {
        cont = cont + 1;
        filas += "<tr>";
        filas += "<td>" + v.numeroIdentificacionBeneficiario + "</td>";
        filas += "<td>" + v.tipoDocumento + "</td>";
        filas += "<td>" + v.nombresBeneficiario +" "+ v.apellidosBeneficiario  + "</td>";
        filas += "<td>" + v.tipoGenero + "</td>";
        filas += "<td>" + v.fechaNacimientoBeneficiario + "</td>";
        //filas += "<td>" + v.numeroIdentificacionFuncionario + "</td>";
        filas += "<td>" + v.nombresFuncionario + " " + v.apellidosFuncionario + "</td>";
        filas += "<td>" + v.direccionBeneficiario + "</td>";
        filas += "<td>" + v.telefonoBeneficiario + "</td>";
        filas += "<td>" + v.movilBeneficiario + "</td>";
        filas += "<td>" + v.correoBeneficiario + "</td>";
        //filas += "<td>" + v.estadoBeneficiario + "</td>";
        filas += "<td>";
        filas += "<form action='" + url_base + "/beneficiarios/editarBeneficiario' method='POST'>";
        filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarBeneficiario'><i class='fa fa-edit'></i></button>";
        filas += "<input type='hidden' name='idBeneficiario' value='" + v.idBeneficiario + "'>";
        filas += "</form>";
        filas += "</td>";
        filas += "<td>";
        filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarBeneficiario" + cont + "' name='btnModalEliminarBeneficiario'><i class='fa fa-close'></i></button>";
        filas += "<div class = 'modal fade' id='modalEliminarBeneficiario" + cont + "' tabindex = '-1' role = 'dialog'>";
        filas += "<div class='modal-dialog'>";
        filas += "<div class='modal-content'>";
        filas += "<div class='modal-header'>";
        filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
        filas += "<h4 class='modal-title'>Eliminar Beneficiario</h4>";
        filas += "</div>";
        filas += "<div class='modal-body'>";
        filas += "<p>¿Seguro que desea eliminar registro?</p>";
        filas += "</div>";
        filas += "<div class='modal-footer'>";
        filas += "<form action='" + url_base + "/beneficiarios/eliminarBeneficiario' method='POST'>";
        filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
        filas += "<button class='btn btn-primary' type='submit' name='btnEliminarBeneficiario'> Aceptar </button>";
        filas += "<input type='hidden' name='idBeneficiario' value='" + v.idBeneficiario + "'>";
        filas += "</form>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</td>";
        filas += "</tr>";
    });
    $('#tblBeneficiarios tbody').html(filas);
});

$('#btnBuscar').click(function () {
    var beneficiario = $('#txtBuscar').val();
    $.post(url_base+'/beneficiarios/listarDocumentoBeneficiario', {beneficiario: beneficiario}, function (data) {
        var datos = JSON.parse(data);
        var cont = 0;
        if (datos != false) {
            var filas;
            $.each(datos, function (i, v) {
                cont = cont + 1;
                filas += "<tr>";
                filas += "<td>" + v.numeroIdentificacionBeneficiario + "</td>";
                filas += "<td>" + v.tipoDocumento + "</td>";
                filas += "<td>" + v.nombresBeneficiario + "</td>";
                filas += "<td>" + v.apellidosBeneficiario + "</td>";
                filas += "<td>" + v.tipoGenero + "</td>";
                filas += "<td>" + v.fechaNacimientoBeneficiario + "</td>";
                filas += "<td>" + v.numeroIdentificacionFuncionario + "</td>";
                filas += "<td>" + v.nombresFuncionario + " " + v.apellidosFuncionario + "</td>";
                filas += "<td>" + v.direccionBeneficiario + "</td>";
                filas += "<td>" + v.telefonoBeneficiario + "</td>";
                filas += "<td>" + v.movilBeneficiario + "</td>";
                filas += "<td>" + v.correoBeneficiario + "</td>";
                filas += "<td>" + v.estadoBeneficiario + "</td>";
                filas += "<td>";
                filas += "<form action='" + url_base + "/beneficiarios/editarBeneficiario' method='POST'>";
                filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarBeneficiario'><i class='fa fa-edit'></i></button>";
                filas += "<input type='hidden' name='idBeneficiario' value='" + v.idBeneficiario + "'>";
                filas += "</form>";
                filas += "</td>";
                filas += "<td>";
                filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarBeneficiario" + cont + "' name='btnModalEliminarBeneficiario'><i class='fa fa-close'></i></button>";
                filas += "<div class = 'modal fade' id='modalEliminarBeneficiario" + cont + "' tabindex = '-1' role = 'dialog'>";
                filas += "<div class='modal-dialog'>";
                filas += "<div class='modal-content'>";
                filas += "<div class='modal-header'>";
                filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
                filas += "<h4 class='modal-title'>Eliminar Beneficiario</h4>";
                filas += "</div>";
                filas += "<div class='modal-body'>";
                filas += "<p>¿Seguro que desea eliminar registro?</p>";
                filas += "</div>";
                filas += "<div class='modal-footer'>";
                filas += "<form action='" + url_base + "/beneficiarios/eliminarBeneficiario' method='POST'>";
                filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
                filas += "<button class='btn btn-primary' type='submit' name='btnEliminarBeneficiario'> Aceptar </button>";
                filas += "<input type='hidden' name='idBeneficiario' value='" + v.idBeneficiario + "'>";
                filas += "</form>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</td>";
                filas += "</tr>";
            });
        } else {
            filas += "<tr>";
            filas += "<td colspan='6'>No existe Beneficiario con este Numero de documento</td>";
            filas += "</tr>";
        }
        $('#tblBeneficiarios tbody').html(filas);
    });
});