var url_base = window.location.protocol + "//" + window.location.host;
$.post(url_base+'/funcionarios/listarFuncionarios', {}, function (data) {
    var datos = JSON.parse(data);
    var filas;
    var cont = 0;
    $.each(datos, function (i, v) {
        cont = cont + 1;
        filas += "<tr>";
        filas += "<td>" + v.numeroIdentificacionFuncionario + "</td>";
        filas += "<td>" + v.tipoDocumento + "</td>";
        filas += "<td>" + v.nombresFuncionario + "</td>";
        filas += "<td>" + v.apellidosFuncionario + "</td>";
        filas += "<td>" + v.tipoGenero + "</td>";
        filas += "<td>" + v.fechaNacimientoFuncionario + "</td>";
        filas += "<td>" + v.nombreCentroFormacion + "</td>";
        filas += "<td>" + v.nombreRegional + "</td>";
        filas += "<td>" + v.direccionFuncionario + "</td>";
        filas += "<td>" + v.telefonoFuncionario + "</td>";
        filas += "<td>" + v.movilFuncionario + "</td>";
        filas += "<td>" + v.correoFuncionario + "</td>";
        filas += "<td>" + v.estadoFuncionario + "</td>";
        filas += "<td>";
        filas += "<form action='" + url_base + "/funcionarios/editarFuncionario' method='POST'>";
        filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarFuncionario'><i class='fa fa-edit'></i></button>";
        filas += "<input type='hidden' name='idFuncionario' value='" + v.idFuncionario + "'>";
        filas += "</form>";
        filas += "</td>";
        filas += "<td>";
        filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarFuncionario" + cont + "' name='btnModalEliminarFuncionario'><i class='fa fa-close'></i></button>";
        filas += "<div class = 'modal fade' id='modalEliminarFuncionario" + cont + "' tabindex = '-1' role = 'dialog'>";
        filas += "<div class='modal-dialog'>";
        filas += "<div class='modal-content'>";
        filas += "<div class='modal-header'>";
        filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
        filas += "<h4 class='modal-title'>Eliminar Funcionario</h4>";
        filas += "</div>";
        filas += "<div class='modal-body'>";
        filas += "<p>¿Seguro que desea eliminar registro?</p>";
        filas += "</div>";
        filas += "<div class='modal-footer'>";
        filas += "<form action='" + url_base + "/funcionarios/eliminarFuncionario' method='POST'>";
        filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
        filas += "<button class='btn btn-primary' type='submit' name='btnEliminarFuncionario'> Aceptar </button>";
        filas += "<input type='hidden' name='idFuncionario' value='" + v.idFuncionario + "'>";
        filas += "</form>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</td>";
        filas += "</tr>";
    });
    $('#tblFuncionarios tbody').html(filas);
});

$('#btnBuscar').click(function () {
    var funcionario = $('#txtBuscar').val();
    $.post(url_base+'/funcionarios/listarDocumentoFuncionario', {funcionario: funcionario}, function (data) {
        var datos = JSON.parse(data);
        var cont = 0;
        if (datos != false) {
            var filas;
            $.each(datos, function (i, v) {
                cont = cont + 1;
                filas += "<tr>";
                filas += "<td>" + v.numeroIdentificacionFuncionario + "</td>";
                filas += "<td>" + v.tipoDocumento + "</td>";
                filas += "<td>" + v.nombresFuncionario + "</td>";
                filas += "<td>" + v.apellidosFuncionario + "</td>";
                filas += "<td>" + v.tipoGenero + "</td>";
                filas += "<td>" + v.fechaNacimientoFuncionario + "</td>";
                filas += "<td>" + v.nombreCentroFormacion + "</td>";
                filas += "<td>" + v.nombreRegional + "</td>";
                filas += "<td>" + v.direccionFuncionario + "</td>";
                filas += "<td>" + v.telefonoFuncionario + "</td>";
                filas += "<td>" + v.movilFuncionario + "</td>";
                filas += "<td>" + v.correoFuncionario + "</td>";
                filas += "<td>" + v.estadoFuncionario + "</td>";
                filas += "<td>";
                filas += "<form action='" + url_base + "/funcionarios/editarFuncionario' method='POST'>";
                filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarFuncionario'><i class='fa fa-edit'></i></button>";
                filas += "<input type='hidden' name='idFuncionario' value='" + v.idFuncionario + "'>";
                filas += "</form>";
                filas += "</td>";
                filas += "<td>";
                filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarFuncionario" + cont + "' name='btnModalEliminarFuncionario'><i class='fa fa-close'></i></button>";
                filas += "<div class = 'modal fade' id='modalEliminarFuncionario" + cont + "' tabindex = '-1' role = 'dialog'>";
                filas += "<div class='modal-dialog'>";
                filas += "<div class='modal-content'>";
                filas += "<div class='modal-header'>";
                filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
                filas += "<h4 class='modal-title'>Eliminar Funcionario</h4>";
                filas += "</div>";
                filas += "<div class='modal-body'>";
                filas += "<p>¿Seguro que desea eliminar registro?</p>";
                filas += "</div>";
                filas += "<div class='modal-footer'>";
                filas += "<form action='" + url_base + "/funcionarios/eliminarFuncionario' method='POST'>";
                filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
                filas += "<button class='btn btn-primary' type='submit' name='btnEliminarFuncionario'> Aceptar </button>";
                filas += "<input type='hidden' name='idFuncionario' value='" + v.idFuncionario + "'>";
                filas += "</form>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</td>";
                filas += "</tr>";
            });
        } else {
            filas += "<tr>";
            filas += "<td colspan='6'>No existe Funcionario con este Numero de documento</td>";
            filas += "</tr>";
        }
        $('#tblFuncionarios tbody').html(filas);
    });
});