var url_base = window.location.protocol + "//" + window.location.host;
$.post(url_base+'/medicamentos/listarMedicamentos', {}, function (data) {
    var datos = JSON.parse(data);
    var filas;
    var cont = 0;
    $.each(datos, function (i, v) {
        cont = cont + 1;
        filas += "<tr>";
        filas += "<td>" + v.codigoMedicamento + "</td>";
        filas += "<td>" + v.nombreGenericoMedicamento + "</td>";
        filas += "<td>" + v.descripcionMedicamento + "</td>";
        filas += "<td>" + v.formaFarmaceuticaMedicamento + "</td>";
        filas += "<td>" + v.concentracionMedicamento + "</td>";
        filas += "<td>" + v.dosisMedicamento + "</td>";
        filas += "<td>" + v.viaFrecuenciaAdministracionMedicamento + "</td>";
        filas += "<td>" + v.registroInvimaMedicamento + "</td>";
        filas += "<td>";
        filas += "<form action='" + url_base + "/medicamentos/editarMedicamento' method='POST'>";
        filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarMedicamento'><i class='fa fa-edit'></i></button>";
        filas += "<input type='hidden' name='idMedicamento' value='" + v.idMedicamento + "'>";
        filas += "</form>";
        filas += "</td>";
        filas += "<td>";
        filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarMedicamento" + cont + "' name='btnModalEliminarRol'><i class='fa fa-close'></i></button>";
        filas += "<div class = 'modal fade' id='modalEliminarMedicamento" + cont + "' tabindex = '-1' role = 'dialog'>";
        filas += "<div class='modal-dialog'>";
        filas += "<div class='modal-content'>";
        filas += "<div class='modal-header'>";
        filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
        filas += "<h4 class='modal-title'>Eliminar Medicamento</h4>";
        filas += "</div>";
        filas += "<div class='modal-body'>";
        filas += "<p>¿Seguro que desea eliminar registro?</p>";
        filas += "</div>";
        filas += "<div class='modal-footer'>";
        filas += "<form action='" + url_base + "/medicamentos/eliminarMedicamento' method='POST'>";
        filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
        filas += "<button class='btn btn-primary' type='submit' name='btnEliminarMedicamento'> Aceptar </button>";
        filas += "<input type='hidden' name='idMedicamento' value='" + v.idMedicamento + "'>";
        filas += "</form>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</div>";
        filas += "</td>";
        filas += "</tr>";
    });
    $('#tblMedicamentos tbody').html(filas);
});

$('#btnBuscar').click(function () {
    var medicamento = $('#txtBuscar').val();
    $.post(url_base+'/medicamentos/listarNombreMedicamento', {medicamento: medicamento}, function (data) {
        var datos = JSON.parse(data);
        var filas;
        cont = 0;
        if (datos != false) {
            $.each(datos, function (i, v) {
                cont = cont + 1;
                filas += "<tr>";
                filas += "<td>" + v.codigoMedicamento + "</td>";
                filas += "<td>" + v.nombreGenericoMedicamento + "</td>";
                filas += "<td>" + v.descripcionMedicamento + "</td>";
                filas += "<td>" + v.formaFarmaceuticaMedicamento + "</td>";
                filas += "<td>" + v.concentracionMedicamento + "</td>";
                filas += "<td>" + v.dosisMedicamento + "</td>";
                filas += "<td>" + v.viaFrecuenciaAdministracionMedicamento + "</td>";
                filas += "<td>" + v.registroInvimaMedicamento + "</td>";
                filas += "<td>";
                filas += "<form action='" + url_base + "/medicamentos/editarMedicamento' method='POST'>";
                filas += "<button class='btn btn-xs btn-success' type='submit' name='btnEditarMedicamento'><i class='fa fa-edit'></i></button>";
                filas += "<input type='hidden' name='idMedicamento' value='" + v.idMedicamento + "'>";
                filas += "</form>";
                filas += "</td>";
                filas += "<td>";
                filas += "<button class='btn btn-xs btn-danger' data-toggle='modal' data-target='#modalEliminarMedicamento" + cont + "' name='btnModalEliminarRol'><i class='fa fa-close'></i></button>";
                filas += "<div class = 'modal fade' id='modalEliminarMedicamento" + cont + "' tabindex = '-1' role = 'dialog'>";
                filas += "<div class='modal-dialog'>";
                filas += "<div class='modal-content'>";
                filas += "<div class='modal-header'>";
                filas += "<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
                filas += "<h4 class='modal-title'>Eliminar Medicamento</h4>";
                filas += "</div>";
                filas += "<div class='modal-body'>";
                filas += "<p>¿Seguro que desea eliminar registro?</p>";
                filas += "</div>";
                filas += "<div class='modal-footer'>";
                filas += "<form action='" + url_base + "/medicamentos/eliminarMedicamento' method='POST'>";
                filas += "<button type='button' class='btn btn-default' data-dismiss='modal'>Cancelar</button>";
                filas += "<button class='btn btn-primary' type='submit' name='btnEliminarMedicamento'> Aceptar </button>";
                filas += "<input type='hidden' name='idMedicamento' value='" + v.idMedicamento + "'>";
                filas += "</form>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</div>";
                filas += "</td>";
                filas += "</tr>";
            });
        } else {
            filas += "<tr>";
            filas += "<td colspan='6'>No existe este Medicamento</td>";
            filas += "</tr>";
        }
        $('#tblMedicamentos tbody').html(filas);
    });
});